const APP_KEY='kaoyan_v7_state';
const state=JSON.parse(localStorage.getItem(APP_KEY)||'{"taskStatus":{},"customTasks":[],"daily":{},"chapter":{}}');
const save=()=>localStorage.setItem(APP_KEY,JSON.stringify(state));
let todayConfig=null, progressConfig=null, activeMap='math', loadedMaps={};

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path);return r.json();}
async function boot(){
  [todayConfig,progressConfig]=await Promise.all([getJson('./data/today.json'),getJson('./data/progress.json')]);
  renderSubjects(); renderToday(); renderHistory(); renderReview(); bind();
}
function bind(){
  $$('.tab').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view,b)));
  $$('.map-tab').forEach(b=>b.addEventListener('click',()=>{activeMap=b.dataset.map;$$('.map-tab').forEach(x=>x.classList.toggle('active',x===b));loadMap(activeMap)}));
  $('#expandAll').addEventListener('click',()=>$$('#mapMain details').forEach(d=>d.open=true));
  $('#collapseAll').addEventListener('click',()=>$$('#mapMain details').forEach(d=>d.open=false));
  $('#addTask').addEventListener('click',addTask); $('#saveDay').addEventListener('click',saveDay);
}
function switchView(v,b){$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.add('hidden'));$('#view-'+v).classList.remove('hidden');if(v==='map'&&!loadedMaps[activeMap])loadMap(activeMap)}
function renderSubjects(){const el=$('#subjectCards');el.innerHTML=progressConfig.subjects.map(s=>`<div class="metric"><span>${s.name}</span><b>${s.percent}%</b><small>${s.note}</small></div>`).join('')}
function allTasks(){return [...todayConfig.tasks,...state.customTasks]}
function renderToday(){
  const tasks=allTasks(), box=$('#todayTasks'); box.innerHTML='';
  tasks.forEach(t=>{const st=state.taskStatus[t.id]||'todo';const card=document.createElement('div');card.className=`task-card ${st}`;card.innerHTML=`<div class="task-top"><div><div class="task-meta">${t.subject} · ${t.minutes}min</div><div class="task-title">${t.title}</div></div><span class="badge">${({todo:'待执行',done:'已完成',partial:'部分完成',stuck:'卡住',delay:'延期'})[st]}</span></div><div class="task-actions"><button data-s="done">完成</button><button data-s="partial">部分完成</button><button data-s="stuck">卡住</button><button data-s="delay">延期</button><button data-edit>修改</button><button data-del>删除</button></div>`;card.querySelectorAll('[data-s]').forEach(b=>b.addEventListener('click',()=>{state.taskStatus[t.id]=b.dataset.s;save();renderToday()}));card.querySelector('[data-edit]').addEventListener('click',()=>editTask(t));card.querySelector('[data-del]').addEventListener('click',()=>deleteTask(t));box.appendChild(card)});
  const done=tasks.filter(t=>(state.taskStatus[t.id]||'todo')==='done').length, rate=tasks.length?Math.round(done/tasks.length*100):0;
  $('#todaySummary').textContent=`${done} / ${tasks.length} 完成`;$('#todayRate').textContent=`${rate}%`;$('#todayBar').style.width=rate+'%';
  $('#todayMini').innerHTML=tasks.map(t=>`<div class="mini">${({todo:'⬜',done:'✅',partial:'🔵',stuck:'🟠',delay:'⏸️'})[state.taskStatus[t.id]||'todo']} ${t.subject}｜${t.title}</div>`).join('')
}
function addTask(){const title=$('#newTaskTitle').value.trim();if(!title)return;state.customTasks.push({id:'custom-'+Date.now(),subject:$('#newTaskSubject').value,title,minutes:Math.max(5,Number($('#newTaskMinutes').value)||30)});$('#newTaskTitle').value='';$('#newTaskMinutes').value='';save();renderToday()}
function editTask(t){const n=prompt('修改任务名称',t.title);if(n===null)return;const m=prompt('修改预计分钟',t.minutes);const ct=state.customTasks.find(x=>x.id===t.id);if(ct){ct.title=n.trim()||ct.title;ct.minutes=Math.max(5,Number(m)||ct.minutes)}else{state.customTasks.push({...t,id:'override-'+t.id,title:n.trim()||t.title,minutes:Math.max(5,Number(m)||t.minutes)});state.taskStatus['override-'+t.id]=state.taskStatus[t.id]||'todo';state.taskStatus[t.id]='delay'}save();renderToday()}
function deleteTask(t){state.customTasks=state.customTasks.filter(x=>x.id!==t.id);state.taskStatus[t.id]='delay';save();renderToday()}
function saveDay(){const k=todayKey();state.daily[k]={actualHours:$('#actualHours').value,mathQa:$('#mathQa').value,csQa:$('#csQa').value,wordMinutes:$('#wordMinutes').value,dayBlock:$('#dayBlock').value.trim(),dayEnergy:$('#dayEnergy').value,tasks:allTasks().map(t=>({...t,status:state.taskStatus[t.id]||'todo'}))};save();renderHistory();renderReview();alert('今日反馈已保存')}
function renderHistory(){const rows=Object.entries(state.daily).sort((a,b)=>b[0].localeCompare(a[0]));const total=rows.reduce((s,[,d])=>s+(Number(d.actualHours)||0),0),done=rows.reduce((s,[,d])=>s+d.tasks.filter(t=>t.status==='done').length,0),stuck=rows.reduce((s,[,d])=>s+d.tasks.filter(t=>t.status==='stuck').length,0);$('#historyStats').innerHTML=`<div class="metric"><span>累计学习</span><b>${total.toFixed(1)}h</b></div><div class="metric"><span>记录天数</span><b>${rows.length}</b></div><div class="metric"><span>完成任务</span><b>${done}</b></div><div class="metric"><span>卡住任务</span><b>${stuck}</b></div>`;$('#historyDays').innerHTML=rows.length?rows.map(([date,d])=>`<div class="history-item"><div class="section-head"><div><b>${date}</b><div class="muted">${d.dayEnergy||'未记录状态'}</div></div><span class="badge">${Number(d.actualHours||0).toFixed(1)}h</span></div><div class="muted">数学 ${d.mathQa||'—'} ｜ 408 ${d.csQa||'—'} ｜ 墨墨 ${d.wordMinutes||0}min</div><div style="margin-top:8px"><b>卡点：</b>${d.dayBlock||'无'}</div><div style="margin-top:10px">${d.tasks.map(t=>`<div class="mini">${({todo:'⬜',done:'✅',partial:'🔵',stuck:'🟠',delay:'⏸️'})[t.status]} ${t.subject}｜${t.title}</div>`).join('')}</div></div>`).join(''):'<div class="empty">还没有学习记录。</div>'}
function renderReview(){const rows=Object.values(state.daily);const stuck=[];rows.forEach(d=>d.tasks.filter(t=>t.status==='stuck').forEach(t=>stuck.push(t)));$('#dueList').innerHTML=stuck.length?stuck.slice(-10).reverse().map(t=>`<div class="history-item">🟠 ${t.subject}｜${t.title}</div>`).join(''):'<div class="empty">暂无待复习。</div>';$('#riskList').innerHTML=stuck.length?stuck.slice(-6).reverse().map(t=>`<div class="history-item">高危：${t.title}</div>`).join(''):'<div class="empty">暂无高危知识点。</div>'}
async function loadMap(key){const main=$('#mapMain');main.innerHTML='<article class="panel"><div class="muted">正在加载学习地图…</div></article>';try{if(!loadedMaps[key])loadedMaps[key]=await getJson(`./data/maps/${key}.json`);renderMap(loadedMaps[key])}catch(e){main.innerHTML='<article class="panel"><b>学习地图加载失败</b><div class="muted">请刷新后重试。</div></article>'}}
function renderMap(data){const main=$('#mapMain');main.innerHTML='';data.groups.forEach((g,gi)=>{const sec=document.createElement('details');sec.className='map-group';sec.open=gi===0;sec.innerHTML=`<summary class="group-summary"><span>${g.name}</span><span class="muted">${g.chapters.length}章</span></summary><div class="chapter-list"></div>`;const list=sec.querySelector('.chapter-list');g.chapters.forEach(ch=>{const rec=state.chapter[ch.id]||{status:ch.status||'unlearned',progress:ch.progress||0};const d=document.createElement('details');d.className=`chapter ${rec.status}`;d.innerHTML=`<summary class="chapter-summary"><div class="chapter-name">${ch.name}</div><div class="chapter-meta">${statusLabel(rec.status)} · ${rec.progress}% · ${ch.topics.length}个知识点</div></summary><div class="topics">${ch.topics.map(t=>`<span class="topic">${t}</span>`).join('')}</div>`;d.addEventListener('toggle',()=>{if(d.open)$('#mapDetail').innerHTML=`<h3>${ch.name}</h3><p class="muted">${ch.topics.length} 个知识点</p><div class="topics">${ch.topics.map(t=>`<span class="topic">${t}</span>`).join('')}</div>`});list.appendChild(d)});main.appendChild(sec)})}
function statusLabel(s){return ({unlearned:'未学',learning:'学习中',review:'已学未稳',due:'待复习',mastered:'已掌握'})[s]||'未学'}
boot().catch(()=>{document.body.insertAdjacentHTML('beforeend','<div style="padding:20px;color:#b42318">初始化失败，请刷新页面。</div>')});
